### ISSUE TITLE
BOOST AND NG SPICE FIX

### ISSUE THREAD

**Issue by chicco83** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#1]
**ng spice version 40 does not exist, actual version is 42, fix "02_Download_Requirement_Files.bat" with this code**

```
rem https://sourceforge.net/projects/ngspice/files/ng-spice-rework/42/
echo ngspice-42 ngspice Files
if not exist ngspice-42.tar.gz DownloadFile https://jaist.dl.sourceforge.net/project/ngspice/ng-spice-rework/42/ngspice-42.tar.gz ngspice-42.tar.gz

if not exist ngspice-42_dll_64.7z DownloadFile https://master.dl.sourceforge.net/project/ngspice/ng-spice-rework/42/ngspice-42_dll_64.7z ngspice-42_dll_64.7z
```
then add the following command to "05_Extract_Requirement_Files.bat" because make file in step 12 expects a folder named "ngspice-40". 
change 

`tar -xf ngspice-40.tar.gz`

into

`tar -xf ngspice-42.tar.gz`

paste the following command after "tar -xf ngspice-42.tar.gz"

`ren ngspice-42 ngspice-40`
`ren ngspice-42_dll_64.7z ngspice-40_dll_64.7z`

**boost is not downloadable from the former link**

change download string with this

`if not exist boost_1_81_0.zip DownloadFile https://sourceforge.net/projects/boost/files/boost/1.81.0/boost_1_81_0.zip `

**Comment by FREEWING-JP** [comment]
Thank you !!
