### ISSUE TITLE
Configuring incomplete at 07 Build Library

### ISSUE THREAD

**Issue by AwayJob** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#13]
Did this on Windows Sandbox in Windows 10.

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/66241829/6ae397ee-d6b9-4eb5-9b67-2aeda7447e52)

Logs:
[CMakeOutput.log](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/files/14155805/CMakeOutput.log)
[CMakeError.log](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/files/14155807/CMakeError.log)

**Comment by FREEWING-JP** [comment]
2024/02/18 I confirmed Build Success .
Please Try Again .
![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/fb525e52-10c1-4945-9114-8059397690c1)

**Comment by FREEWING-JP** [comment]
I confirmed build so close .
