### ISSUE TITLE
Fritzing 1.0.2 crashes hard when I press Simulate button :(

### ISSUE THREAD

**Issue by FREEWING-JP** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#16]
https://youtu.be/cC82PULJq6g

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/bcf8a2cf-d227-4b96-854d-69f8493914ca)

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/9ced3155-9d08-4557-a9aa-1ca0658e66de)

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/dc758677-0819-49e5-ba28-f2e6030c0659)

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/4cf37376-8d9d-4fff-8167-09fc3ca8cecf)

Then Fritzing 1.0.2 Crash .

**Comment by FREEWING-JP** [comment]
https://github.com/fritzing/fritzing-app/issues/3977

Related Ngspice library ?
https://ngspice.sourceforge.io/shared.html

https://github.com/fritzing/fritzing-app/tree/develop/src/simulation

**Comment by EngineerForce** [comment]
Thank you for the amazing script you build to compile Fritzing.

Did adding the Ngspice dll solve this issue?

**Comment by a-crazy-pencil** [comment]
yes

**Comment by FREEWING-JP** [comment]
Thank you !
Add ngspice-42_dll_64.7z's these dll to Fritzing.exe directory to solved .
* libomp140.x86_64.dll
* ngspice.dll

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/eff12cc9-b524-4b18-9091-1b769842d43f)

**Comment by FREEWING-JP** [comment]
fixed 
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/17
