### ISSUE TITLE
Script 07_Build_Library.bat Failed

### ISSUE THREAD

**Issue by afdhal395** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#18]
I ran the script using the suggested method which is start the process by the bitsadmin command. On the execution of the 07_Build_Library.bat, I encounter error as below. 

My build system is newly installed Windows 10 64bit.

```
07_Build_Library.bat

Waiting for  0 seconds, press CTRL+C to quit ...
The system cannot find the path specified.
Build Boost
Building Boost.Build engine
could not find "vswhere"
Call_If_Exists "Auxiliary\Build\vcvarsall.bat"  AMD64
###
### Using 'vc142' toolset.
###

C:\00_fritzing\boost_1_81_0\tools\build\src\engine>"cl" /nologo /MP /MT /TP /Feb2 /wd4996 /O2 /GL /EHsc   -DNDEBUG  builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp execnt.cpp execunix.cpp filent.cpp filesys.cpp fileunix.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathnt.cpp pathsys.cpp pathunix.cpp regexp.cpp rules.cpp scan.cpp search.cpp jam_strings.cpp startup.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp /link kernel32.lib advapi32.lib user32.lib
'"cl"' is not recognized as an internal or external command,
operable program or batch file.

C:\00_fritzing\boost_1_81_0\tools\build\src\engine>dir *.exe
 Volume in drive C has no label.
 Volume Serial Number is 58AA-2BE7

 Directory of C:\00_fritzing\boost_1_81_0\tools\build\src\engine

File Not Found

Failed to build Boost.Build engine.

C:\00_fritzing\boost_1_81_0
'b2.exe' is not recognized as an internal or external command,
operable program or batch file.
.
===
failed
===

Waiting for  0 seconds, press CTRL+C to quit ...
```

**Comment by FREEWING-JP** [comment]
Please try running again.
I think it's a temporary network problem.

**Comment by FREEWING-JP** [comment]
Build Fritzing 1.0.2 (Reconfirmed on 2024/04/13)

**Comment by MalGamerz** [comment]
07_Build_Library.bat

Waiting for  0 seconds, press CTRL+C to quit ...
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.11.35
** Copyright (c) 2021 Microsoft Corporation
**********************************************************************
Build Boost
'bootstrap.bat' is not recognized as an internal or external command,
operable program or batch file.
C:\00_fritzing\boost_1_81_0
'b2.exe' is not recognized as an internal or external command,
operable program or batch file.
.
===
failed
===

Waiting for  0 seconds, press CTRL+C to quit ...

Waiting for  0 seconds, press CTRL+C to quit ...

Waiting for  3 seconds, press CTRL+C to quit ...

I have the same problems as well
