### ISSUE TITLE
07_Build_Library.bat

### ISSUE THREAD

**Issue by MalGamerz** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#19]
07_Build_Library.bat

Waiting for 0 seconds, press CTRL+C to quit ...

** Visual Studio 2019 Developer Command Prompt v16.11.35
** Copyright (c) 2021 Microsoft Corporation

Build Boost
'bootstrap.bat' is not recognized as an internal or external command,
operable program or batch file.
C:\00_fritzing\boost_1_81_0
'b2.exe' is not recognized as an internal or external command,
operable program or batch file.
.
failed
Waiting for 0 seconds, press CTRL+C to quit ...

Waiting for 0 seconds, press CTRL+C to quit ...

Waiting for 3 seconds, press CTRL+C to quit ...

My internet is working well and I have rerun this for like a hundred time and still spouting the same error

**Comment by MalGamerz** [comment]
Actually nvm, I've managed to fix the issues by extracting the boost file manually, it's seems that it has some problems by not extracting it completely which makes it's broken, maybe u can add a command line to check that? Like extracting the file back and check whether all the file exist or not

**Comment by FREEWING-JP** [comment]
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/issues/18#issuecomment-2088846128

**Comment by FREEWING-JP** [comment]
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/20

**Comment by FREEWING-JP** [comment]
[Build confirmed .](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/20#issuecomment-2094812143)
