### ISSUE TITLE
CMakeLists.txt pb in 07_Build_Library ?

### ISSUE THREAD

**Issue by Antonin-m84** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#22]
By running the number 7, after 5min i have this problem with libgit2 ?
Can you help me ? :)
thx

![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/105228978/966d0179-5dfd-4764-bbf8-12a4df47eb05)

**Comment by FREEWING-JP** [comment]
It is not intended to be executed on anything other than the C drive .
Try C: drive with Sandbox .

**Comment by Antonin-m84** [comment]
Same problem :(

...updated 88 targets...
Build libgit2
Le chemin d’accès spécifié est introuvable.
CMake Error: The source directory "C:/Users/Antonin/Documents/00_fritzing" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
.
===
failed
===

**Comment by Antonin-m84** [comment]
After a while i got the solution !
00_fritzing MUST be in C:\ root like that : **C:\00_fritzing** and especially not further...

I also had another problem. I forgot to confirm my QT account (check mailbox)... At the end of 07_Build_Library : It gives me an error because it cannot find "QT6" -> QT was not installed correctly because it could not access my account ;)

a huge thank you for this script FREEWING-JP :)
