### ISSUE TITLE
"The system cannot find the path specified" in 13_Build_phoenix_pro_with_Qt.bat

### ISSUE THREAD

**Issue by akarak** [FREEWING-JP/Build-Fritzing-1.0.0-Windows-script#8]
![2024-01-26_105556](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/1761074/c4f8a6b6-7a1e-45e1-8ef7-617845a5e5a2)

**Comment by akarak** [comment]
![2024-01-26_120541](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/1761074/0194fad6-6c6b-4e1a-a2a0-527d5a293425)

**Comment by FREEWING-JP** [comment]
2nd issue . 
Looks like Your IP address is Blocked by Qt .
![image](https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/assets/16265606/f680ee13-3e58-4763-a947-a325cd786903)

**Comment by FREEWING-JP** [comment]
1st issue .
I don't know if this is the cause, but I fixed "zlib 1.3.1” for now.
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/7
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/9

**Comment by FREEWING-JP** [comment]
https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/pull/11

I confirmed that the build was successful .

**Comment by FREEWING-JP** [comment]
I confirmed build so close .
